CW2_WebClient/Models/Login.cs
using System.ComponentModel.DataAnnotations;

namespace CW2_WebClient.Models
{
    public class Login
    {
        [Required]
        [Display(Name = "Usuário")]
        public string? login { get; set; }

        [Required]
        [Display(Name = "Senha")]
        public string? senha { get; set; }
    }
}

CW2_WebClient/Models/Usuario.cs
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace CW2_WebClient.Models
{
    public class Usuario
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Nome")]
        public string? Nome { get; set; }

        [Required]
        [Display(Name = "Usuário")]
        public string? login { get; set; }

        [Required]
        [Display(Name = "Ativo")]
        public bool Ativo { get; set; }

        [Required]
        [Display(Name = "Senha")]
        public string? Senha { get; set; }

        [Required]
        [Display(Name = "E-mail")]
        public string? Email { get; set; }
    }
}

CW2_WebClient/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;

namespace CW2_WebClient.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

CW2_WebClient/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace CW2_WebClient.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

CW2_WebClient/Pages/HomePage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CW2_WebClient.Pages
{
    public class HomePageModel : PageModel
    {
        public string Username { get; set; }
        public IActionResult OnGet()
        {
            Username = HttpContext.Session.GetString("usuario");

            if (string.IsNullOrWhiteSpace(Username))
            {
                return Redirect("/login");
            }

            return Page();
        }

        public IActionResult OnGetLogout()
        {
            HttpContext.Session.Remove("usuario");
            return RedirectToPage("/Login");
        }
    }
}

CW2_WebClient/Pages/Index2.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CW2_WebClient.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

CW2_WebClient/Pages/Login.cshtml.cs
using CW2_WebClient.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using System.Net.Http;
using System;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;
using System.Security.Cryptography;

namespace CW2_WebClient.Pages
{
    [AllowAnonymous]
    public class LoginModel : PageModel
    {
        private readonly Data.LoginDbContext _context;

        public LoginModel(Data.LoginDbContext context)
        {
            _context = context;
        }
        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Login? Login { get; set; }

        [TempData]
        public bool errologin { get; set; } = false;

        public async Task<IActionResult> OnPostAsync([FromServices] IConfiguration config)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            

            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(
                    new MediaTypeWithQualityHeaderValue("application/json"));

                string baseURL =
                    config.GetSection("API_Login:BaseURL").Value;

                Login.senha = GerarMD5(Login.senha);

                var myContent = JsonConvert.SerializeObject(Login);
                var buffer = System.Text.Encoding.UTF8.GetBytes(myContent);
                var byteContent = new ByteArrayContent(buffer);

                byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");

                var response = await client.PostAsync(baseURL, byteContent);

                if (response.StatusCode == System.Net.HttpStatusCode.NotFound)
                {
                    errologin = true;
                    return Page();
                }

                response.EnsureSuccessStatusCode();
                errologin = false;
                string conteudo =
                    response.Content.ReadAsStringAsync().Result;

                HttpContext.Session.SetString("usuario", Login.login);
            }

            return Redirect("/HomePage");
        }

        public string GerarMD5(string valor)
        {
            MD5 md5Hasher = MD5.Create();
            byte[] valorCriptografado = md5Hasher.ComputeHash(Encoding.Default.GetBytes(valor));
            StringBuilder strBuilder = new StringBuilder();

            for (int i = 0; i < valorCriptografado.Length; i++)
            {
                strBuilder.Append(valorCriptografado[i].ToString("x2"));
            }

            return strBuilder.ToString();
        }
    }
}

CW2_WebClient/Pages/Prestadores.cshtml.cs
using CW2_WebClient.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using System.Net.Http.Headers;

namespace CW2_WebClient.Pages
{
    public class PrestadoresModel : PageModel
    {
        [BindProperty]
        public Prestador? prestador { get; set; }

        [TempData]
        public bool sucessoCadastro { get; set; } = false;

        public List<Prestador>? prestadores_cadastrados { get; set; }
        public string Username { get; set; }
        public async Task<IActionResult> OnGet([FromServices] IConfiguration config)
        {
            Username = HttpContext.Session.GetString("usuario");

            if (string.IsNullOrWhiteSpace(Username))
            {
                return Redirect("/login");
            }

            await this.AtualizarPrestadoresCadastrados(config);
            sucessoCadastro = false;
            return Page();
        }

        public async Task<IActionResult> OnPostAsync([FromServices] IConfiguration config)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(
                    new MediaTypeWithQualityHeaderValue("application/json"));

                string baseURL =
                    config.GetSection("API_Prestador:BaseURL").Value;

                var myContent = JsonConvert.SerializeObject(prestador);
                var buffer = System.Text.Encoding.UTF8.GetBytes(myContent);
                var byteContent = new ByteArrayContent(buffer);

                byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");

                var response = await client.PostAsync(baseURL, byteContent);

                response.EnsureSuccessStatusCode();
                sucessoCadastro = true;

                this.LimparTela();

                string conteudo =
                    response.Content.ReadAsStringAsync().Result;
                await this.AtualizarPrestadoresCadastrados(config);
            }

            return Page();
        }

        private void LimparTela()
        {
            prestador.cgccpf = String.Empty;
            prestador.Nome = String.Empty;
        }

        private async Task<bool> AtualizarPrestadoresCadastrados(IConfiguration config)
        {
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(
                    new MediaTypeWithQualityHeaderValue("application/json"));

                string baseURL =
                    config.GetSection("API_Prestador:BaseURL").Value;

                var response = await client.GetAsync(baseURL);
                string conteudo = response.Content.ReadAsStringAsync().Result;
                var myContent = JsonConvert.DeserializeObject<List<Prestador>>(conteudo);
                prestadores_cadastrados = myContent;
            }

            return true;
        }
    }
}

CW2_WebClient/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CW2_WebClient.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

CW2_WebClient/Pages/Usuarios.cshtml.cs
using CW2_WebClient.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using System.Net.Http.Headers;

namespace CW2_WebClient.Pages
{
    public class UsuariosModel : PageModel
    {
        [BindProperty]
        public Usuario? usuario { get; set; }

        [TempData]
        public bool sucessoCadastro { get; set; } = false;

        public string Username { get; set; }
        public IActionResult OnGet()
        {
            Username = HttpContext.Session.GetString("usuario");

            if (string.IsNullOrWhiteSpace(Username))
            {
                return Redirect("/login");
            }

            sucessoCadastro = false;
            return Page();
        }

        public async Task<IActionResult> OnPostAsync([FromServices] IConfiguration config)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(
                    new MediaTypeWithQualityHeaderValue("application/json"));

                string baseURL =
                    config.GetSection("API_Usuario:BaseURL").Value;

                var myContent = JsonConvert.SerializeObject(usuario);
                var buffer = System.Text.Encoding.UTF8.GetBytes(myContent);
                var byteContent = new ByteArrayContent(buffer);

                byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");

                var response = await client.PostAsync(baseURL, byteContent);

                response.EnsureSuccessStatusCode();
                sucessoCadastro = true;

                string conteudo =
                    response.Content.ReadAsStringAsync().Result;
            }

            return Page();
        }
    }
}

CW2_WebClient/Pages/HomePage.cshtml
@page
@model CW2_WebClient.Pages.HomePageModel
@{
}
<h1>Bem-Vinda(o) @Model.Username</h1>
<a asp-page-handler="Logout">Sair</a>

CW2_WebClient/Pages/Index2.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CW2_WebClient/Pages/Login.cshtml
@page
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model CW2_WebClient.Pages.LoginModel
@{
    ViewData["Title"] = "Login";
    Layout = "~/Pages/Shared/_Layout_Login.cshtml";
}

<div class="container border" style="padding: 20px">
    <form method="post">
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="Login.login"></label>
            </div>
            <div class="col-5">
                <input type="text" asp-for="Login.login" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="Login.senha"></label>
            </div>
            <div class="col-5">
                <input type="password" asp-for="Login.senha" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <input type="submit" class="btn btn-primary" value="Entrar" />
            </div>
        </div>
    </form>
</div>

@if(@Model.errologin){
<div class="alert alert-danger">
    Usuário não encontrado
</div>
}




<style>
    .form-group {
        margin-bottom: 1rem;
    }
</style>

CW2_WebClient/Pages/Prestadores.cshtml
@page
@model CW2_WebClient.Pages.PrestadoresModel
@{
}
@if (@Model.sucessoCadastro)
{
    <div class="alert alert-success">
        Prestador cadastrado com sucesso
    </div>
}

<div class="container border" style="padding: 20px">
    <form method="post">
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="prestador.Nome"></label>
            </div>
            <div class="col-5">
                <input type="text" asp-for="prestador.Nome" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="prestador.cgccpf"></label>
            </div>
            <div class="col-5">
                <input type="text" asp-for="prestador.cgccpf" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <input type="submit" class="btn btn-primary" value="Cadastrar" />
            </div>
        </div>
    </form>
</div>
<h3>Prestadores Cadastrados</h3>
<div class="container border">
    <div class="form-group row">
        <div class="col-5">
            CGC ou CPF
        </div>
        <div class="col-5">
            Nome
        </div>
    </div>

    @foreach (var prestador in Model.prestadores_cadastrados)
    {
        <div class="form-group row">
            <div class="col-5">
                @prestador.cgccpf
            </div>
            <div class="col-5">
                @prestador.Nome
            </div>
        </div>
    }
</div>

CW2_WebClient/Pages/Usuarios.cshtml
@page
@model CW2_WebClient.Pages.UsuariosModel
@{
    ViewData["Title"] = "Usuarios";
}

@if(@Model.sucessoCadastro){
    <div class="alert alert-success">
        Usuário cadastrado com sucesso
    </div>
}

<div class="container border" style="padding: 20px">
    <form method="post">
         <div class="form-group row">
            <div class="col-2">
                <label asp-for="usuario.Nome"></label>
            </div>
            <div class="col-5">
                <input type="text" asp-for="usuario.Nome" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="usuario.Email"></label>
            </div>
            <div class="col-5">
                <input type="text" asp-for="usuario.Email" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="usuario.login"></label>
            </div>
            <div class="col-5">
                <input type="text" asp-for="usuario.login" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="usuario.Senha"></label>
            </div>
            <div class="col-5">
                <input type="password" asp-for="usuario.Senha" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <input type="submit" class="btn btn-primary" value="Cadastrar" />
            </div>
        </div>
    </form>
</div>

<h3>Usuarios Cadastrados</h3>
<div class="container border">
    <div class="form-group row">
        <div class="col-4">
            Nome
        </div>
        <div class="col-4">
            Email
        </div>
        <div class="col-4">
            Login
        </div>
    </div>

    @foreach (var usuario in Model.usuarios_cadastrados)
    {
        <div class="form-group row">
            <div class="col-4">
                @usuario.Nome
            </div>
            <div class="col-4">
                @usuario.Email
            </div>
            <div class="col-4">
                @usuario.login
            </div>
        </div>
    }
</div>